site_name: aoc.py
site_author: nekitdev
site_description: Advent of Code in Python.

repo_name: nekitdev/aoc.py
repo_url: https://github.com/nekitdev/aoc.py

remote_branch: github-pages

nav:
  - Index: "index.md"
  - Usage: "usage.md"
  - Reference:
    - Solutions: "reference/solutions.md"
    - Runners: "reference/runners.md"
    - Timers: "reference/timers.md"
    - Primitives: "reference/primitives.md"
    - Names: "reference/names.md"
    - Errors: "reference/errors.md"
    - Tokens: "reference/tokens.md"
    - Data: "reference/data.md"
    - Time: "reference/time.md"
    - States: "reference/states.md"
    - HTTP: "reference/http.md"
    - Versions: "reference/versions.md"
    - Constants: "reference/constants.md"
    - Extensions:
      - Constants: "reference/ext/constants.md"
      - Splits: "reference/ext/splits.md"
  - Changelog: "changelog.md"
  - Security: "security.md"
  - Code of Conduct: "code_of_conduct.md"
  - Contributing: "contributing.md"

watch:
  - aoc
  - docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: light blue
      accent: deep purple

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_signature_annotations: true

          paths: [aoc]

          import:
            - https://docs.python.org/3/objects.inv
            - https://nekitdev.github.io/typing-aliases/objects.inv
            - https://nekitdev.github.io/versions/objects.inv

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
